### ISSUE TITLE
Objectives Spreadsheet link is broken

### ISSUE THREAD

**Issue by raboley** [towbes/ffxi#3]
Hi towbes! Thank you so much for your hard work on all this stuff, it looks awesome! It looks like the link to the hex values for your Objectives addon is broken. If you still have the data I would love to get it in some form! This addon is something I have been looking for, for a while, so Happy I finally found something that looks like it should work!

Cheers! 👍

**Comment by towbes** [comment]
Ah sorry I'm not sure what happened to the spreadsheet, I looked around through my files but couldn't find a backup copy. 

You can use the addon to obtain the hex values for common ones you will use:

/objectives write - Toggles writing RoE Hex + Description to Ashita folder/roelogs
With write enabled, hex id + description will be written to file when accepting a new RoE objective

I usually ended up just enabling copycat on my main toon, and getting the objectives manually on main window which sent the command out to other boxes using multisend.

**Comment by raboley** [comment]
darn, well I actually found one floating around with all the IDs in decimal. after some testing, it looks like the hexadecimal IDs that your addon use, convert very nicely to decimal.

for example: "Deal 500+ Damage"
in your addon expects the id to be: `0x10`
and in my list it should be `16`. Using a basic hexadecimal converter I can convert all those decimals to hex, but if you plan on working on that addon in the future, it might be more user friendly to have your addon convert the decimal ids to hex, and then add this list of all the ROE tasks.
[RoE-NoBlanks.txt](https://github.com/towbes/ffxi/files/5823688/RoE-NoBlanks.txt)

**Comment by raboley** [comment]
My use case is to update ROE as I switch zones, so it is super helpful to just be able to know all of them, and then do converting later.

**Comment by towbes** [comment]
Ah very good idea!

Yep that list is way more than my spreadsheet ever was lol.  I probably won't be working on the addon anymore, but I will take this txt list and add the hex values then post it in the github!

**Comment by raboley** [comment]
sounds good! thanks again for your hard work and appreciate your responsiveness!

**Comment by towbes** [comment]
Thanks @raboley I added the txt file here!

https://github.com/towbes/ffxi/blob/master/objectives/hexvalues.txt

**Comment by raboley** [comment]
you're the best!
